title: Shubzilla
email: shubzillamusic@gmail.com
description: Shubzilla - Artist
baseurl: "https://shubzilla.github.io"
localhost: 4000
mainhost: "http://localhost:4000"
url: "shubzillamusic.com"
twitter_username: ""
github_username:  ""

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
plugins:
  - jekyll-feed
defaults:
  - scope:
      path: "assets/"
    values:
      image: true
